### ISSUE TITLE
Crystal ANN - web app to announce new Crystal projects, blog posts, updates and other work activities

### ISSUE THREAD

**Issue by veelenga** [unicodeveloper/awesome-opensource-apps#34]
Hey there and thanks for a nice list 👍 ❤️ 

I'm one of the authors of Crystal ANN, the web app running on [Crystal](https://crystal-lang.org/) and [Amber Framework](https://amberframework.org/). This may be (or may be not) the first open sourced web app in this group.

<img src="https://media.githubusercontent.com/media/veelenga/bin/master/crystal-ann/ipad_mockup.png" width="600" />

* [Web link](https://crystal-ann.com/)
* [Github repo](https://github.com/crystal-community/crystal-ann)

Would you add it to the list if I open a PR?

**Comment by unicodeveloper** [comment]
Yes, I would. Please go ahead and submit a PR. Thanks!
